### ISSUE TITLE
Does this library work with Cake 3.1?

### ISSUE THREAD

**Issue by soroshsabz** [Redth/Cake.SemVer#20] opened 2023-10-31 11:06 UTC
ITNOA

Does this dsl work with Cake 3.1?

```
The assembly 'Cake.SemVer, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.33.0).
```

**Comment by nils-a** [comment] 2023-10-31 22:23
The warning you are seeing is a duplicate of #17. 
And yes - this library still works with cake 3.1

**Closed as not planned by nils-a** 2023-10-31 22:23 UTC
